service: hello-go-gin-lambda

provider:
  name: aws
  region: us-east-1
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - http:
          path: /
          method: post
