service: hello-go-gin

provider:
  name: aws
  region: ap-southeast-1
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - http:
          path: /
          method: GET
